### PR TITLE
fix: configure plugins on tsconfig.dev.json

### LINKED ISSUE #5: Compiler plug-ins missing from tsconfig.dev.json
See https://github.com/functionless/functionless/issues/220

### PR DESCRIPTION
**Pull request by sam-goodwin**
Fixes #5 

We were not adding the compiler plugins to the `tsconfig.dev.json`, so tests were not running the transformer plugin and therefore functionless was broken.

This change updates the `Functionless` projen `Component` to add the plugins to `tsconfig.dev.json`. No change is required from the user - just update to the new version.

### CODE REVIEW

File: src/component.ts [hunk 1]
```diff
@@ -23,21 +98,30 @@ export class Functionless extends Component {
...
+              // we don't want to rely on that always being true
+              [...config.compilerOptions.plugins]
+            : []);
+
+        plugins.push({
+          transform: `${Functionless.coreDependency}/lib/compile`,
+        });
+        plugins.push({
+          name: Functionless.languageServiceDependency,
+        });
```
Comment (sam-goodwin) [inline src/component.ts]: Do I need to configure the language service plugin on tsconfig.dev.json, problably not?

File: API.md [hunk 2]
```diff
@@ -1,6 +1,662 @@
 # API Reference <a name="API Reference" id="api-reference"></a>
 
 
+## Structs <a name="Structs" id="Structs"></a>
+
+### TypeScriptCompilerOptionsExtended <a name="TypeScriptCompilerOptionsExtended" id="@functionless/projen.TypeScriptCompilerOptionsExtended"></a>
```
Comment (sam-goodwin) [inline API.md]: Ew, this included the entire interface ...

**Review by thantos — APPROVED** [review]

File: src/component.ts (hunk 1 above)
Comment (thantos) [reply src/component.ts]: Dev is used for the tests. Don't think it'll be ready by the ide unless they change it
